pipeline {
    agent any

    stages {
        stage('Pull Docker Image') {
            steps {
                sh 'docker pull nginx'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d --name mynginx -p 8080:80 nginx'
            }
        }

        stage('Check Running Containers') {
            steps {
                sh 'docker ps'
            }
        }
    }
}
